### ISSUE TITLE
大大能不能支持一下安卓10跟11，MIUI12、12.5

### ISSUE THREAD

**Issue by Heaven7528** [Xposed-Modules-Repo/com.gswxxn.xmsfnotichannel#1]

**Comment by GSWXXN** [comment]
刚刚发了个新版本, 你试一下这个呗 
https://github.com/Xposed-Modules-Repo/com.gswxxn.xmsfnotichannel/releases/tag/111-1.1.1

**Comment by Heaven7528** [comment]
> 

🙏多谢大大
